version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4
workflows:
  version: 2
  test-and-release:
    jobs:      
      - release-management/release-package:
          sign: true
          github-release: true
          filters:
            branches:
              only: main